### PR TITLE
README.md: Fix typo in HTTPS port number

### PR DESCRIPTION
**Pull request by amirnejati**
README.md: Fix typo in HTTPS port number

### CODE REVIEW

**Review by davidebeatrici — APPROVED** [review]

**Comment by davidebeatrici** [comment]
Could you change the commit message to something more descriptive such as `README.md: Fix typo in HTTPS port number`, please?

**Comment by amirnejati** [comment]
> Could you change the commit message to something more descriptive such as `README.md: Fix typo in HTTPS port number`, please?

**Comment by amirnejati** [comment]
Yes, of-course. Just changed

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!

**Comment by amirnejati** [comment]
It's my pleasure.

**Pull request merged**
